
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class LoginStudent extends javax.swing.JFrame {

    /**
     * Creates new form LoginStudent
     */
    Connection con = null;
    PreparedStatement ps = null;
    StudentTb stt = new StudentTb();
    //String facname;
    //String other;
    public LoginStudent() {
        initComponents();
        lblU.setVisible(false);
        lblP.setVisible(false);
        con = MyConnection.getconnection();
        
       // System.out.println();
        
    }

    /**-*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblU;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField pfield1;
    private javax.swing.JButton signbtn;
    private javax.swing.JTextField tfield1;
    // End of variables declaration//GEN-END:variables
}
